### ISSUE TITLE
Submission for assignment 1 

### ISSUE THREAD

**Issue by anhtuanlee** [dwarvesf/df-frontend-2023#2]
Link demo : https://assignment-1-anhtuanlee.vercel.app/

**Comment by zlatanpham** [comment]
Hey @anhtuanlee, can you move your submission to your forked repo?

<img width="821" alt="image" src="https://github.com/dwarvesf/df-frontend-2023/assets/12707960/9bbdab73-6fcf-4630-ab8f-e36bd2faf0c1">
